apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openmq
    spec:
      containers:
      - name: openmq
        image: payara/server-full:5.181
        command: ["/opt/payara5/mq/bin/imqbrokerd"]
        ports:
        - name: openmq
          protocol: TCP
          containerPort: 7676
