apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payara
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payara
    spec:
      containers:
      - name: payara
        image: payara/server-full:5.181
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        - name: https
          protocol: TCP
          containerPort: 8181
        - name: https-admin
          protocol: TCP
          containerPort: 4848
