apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sobas.kazusato.local
spec:
  scope: Namespaced
  group: kazusato.local
  version: v1alpha1
  names:
    kind: Soba
    singular: soba
    plural: sobas
